apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - namespace.yaml
    - ../../app/backend/overlays/dev
    - ../../app/cache/overlays/dev
    - ../../app/frontend/overlays/dev
    - ../../monitoring/dev
