apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: frontend-metrics
    labels:
        app: frontend
        release: prometheus
spec:
    selector:
        matchLabels:
            app: frontend
    endpoints:
        - port: http
          path: /metrics
          interval: 30s
